---
 
- hosts: host1
  become: yes

  roles:
      - {role: role-git}
      - {role: role-java}
      - {role: role-maven}
      - {role: role-docker}
      - {role: role-jenkins}
      - {role: role-wget}


  tasks:
  - name: Upgrade all yum packages ansible.
    yum:
      name: "*"
      state: latest

 
