---
- hosts: host3
  become: yes
  roles:
      - {role: role-git}
      - {role: role-java}
      - {role: role-maven}
      - {role: role-docker}
      - {role: role-wget}
  
  tasks:
  - name: Upgrade all yum packages ansible.
    yum:
      name: "*"
      state: latest

  - name: Copy the docker-compose nexus
    copy: 
      src: /etc/ansible/sonarqube-docker/docker-compose.yml
      dest: /home/desai_ajay_hnr/docker-compose.yml
      mode: '0777'
      
  - name: docker-compose up
    command: docker-compose up -d --build
    args: 
      chdir: /home/desai_ajay_hnr
