---
dependencies: []

galaxy_info:
  author: vasu
  description: Ansible role to install Oracle Java
  license: MIT
  company: "DevOps Techie"
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - all
  galaxy_tags:
    - development
    - system
