---
- name: Check current docker-compose version.
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Install Docker Compose
  yum: 
    name: docker-compose 
    state: installed
